/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedRecepcionRouteImport } from './routes/_authenticated/recepcion'
import { Route as AuthenticatedEcusIndexRouteImport } from './routes/_authenticated/ecus/index'
import { Route as AuthenticatedEcusIdRouteImport } from './routes/_authenticated/ecus/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecepcionRoute = AuthenticatedRecepcionRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcusIndexRoute = AuthenticatedEcusIndexRouteImport.update({
  id: '/ecus/',
  path: '/ecus/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcusIdRoute = AuthenticatedEcusIdRouteImport.update({
  id: '/ecus/$id',
  path: '/ecus/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/recepcion': typeof AuthenticatedRecepcionRoute
  '/ecus/$id': typeof AuthenticatedEcusIdRoute
  '/ecus/': typeof AuthenticatedEcusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/recepcion': typeof AuthenticatedRecepcionRoute
  '/ecus/$id': typeof AuthenticatedEcusIdRoute
  '/ecus': typeof AuthenticatedEcusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/recepcion': typeof AuthenticatedRecepcionRoute
  '/_authenticated/ecus/$id': typeof AuthenticatedEcusIdRoute
  '/_authenticated/ecus/': typeof AuthenticatedEcusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/inventario'
    | '/panel'
    | '/recepcion'
    | '/ecus/$id'
    | '/ecus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/inventario'
    | '/panel'
    | '/recepcion'
    | '/ecus/$id'
    | '/ecus'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/clientes'
    | '/_authenticated/inventario'
    | '/_authenticated/panel'
    | '/_authenticated/recepcion'
    | '/_authenticated/ecus/$id'
    | '/_authenticated/ecus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepcion': {
      id: '/_authenticated/recepcion'
      path: '/recepcion'
      fullPath: '/recepcion'
      preLoaderRoute: typeof AuthenticatedRecepcionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecus/': {
      id: '/_authenticated/ecus/'
      path: '/ecus'
      fullPath: '/ecus/'
      preLoaderRoute: typeof AuthenticatedEcusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecus/$id': {
      id: '/_authenticated/ecus/$id'
      path: '/ecus/$id'
      fullPath: '/ecus/$id'
      preLoaderRoute: typeof AuthenticatedEcusIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedRecepcionRoute: typeof AuthenticatedRecepcionRoute
  AuthenticatedEcusIdRoute: typeof AuthenticatedEcusIdRoute
  AuthenticatedEcusIndexRoute: typeof AuthenticatedEcusIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedRecepcionRoute: AuthenticatedRecepcionRoute,
  AuthenticatedEcusIdRoute: AuthenticatedEcusIdRoute,
  AuthenticatedEcusIndexRoute: AuthenticatedEcusIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
